### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by theanuragsrivastava** [iamaaditya/VQA_Demo#16]
File "demo.py", line 114
    print str(round(y_output[0,label]*100,2)).zfill(5), "% ", labelencoder.inverse_transform(label)
            ^
How do I resolve this error? Please help.

**Comment by tarana-shahin** [comment]
hey anurgsrivastava  how did you resolve this error?

**Comment by anurgsrivastava** [comment]
I don't completely remember but I believe the author fixed the issue by updating his notebook to run with Keras 2.1+ and Tensorflow 1.5+. I remember following the updated README had solved the issue for me. The issue was happening due to the difference in the dimensions of the array. Can be the same for you also please check. Apologies I couldn't help much, it has been some time now.

**Comment by iamaaditya** [comment]
@anurgsrivastava could you provide more detail about the error (the trace). Are you using Python 2 or 3? In Python 3, you need to use `print()` (with parenthesis).

I will take a look at the code and will try to fix any other bugs that it may have.

**Comment by anurgsrivastava** [comment]
@iamaaditya I wasn't having any issue. @tarana-shahin was having some issues. Also, thank you for this project, it saved me during my college. 🥇
